# Generated by Django 5.1.7 on 2025-03-23 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField()),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='queueapp.queue')),
            ],
        ),
    ]
