# Generated by Django 5.1.7 on 2025-03-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0002_queueparticipant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='description',
            new_name='address',
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(default='11111111111', max_length=15),
        ),
    ]
