# Generated by Django 5.1.7 on 2025-03-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0003_rename_description_business_address_business_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='queueapp.business'),
        ),
    ]
