# Generated by Django 5.1.7 on 2025-03-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0004_alter_queue_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queueapp.business'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
