# Generated by Django 5.1.7 on 2025-03-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0005_alter_queue_business_alter_queue_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueparticipant',
            name='served',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='queue',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='queueapp.business'),
        ),
    ]
