# Generated by Django 5.1.7 on 2025-03-25 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0006_queueparticipant_served_alter_queue_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueparticipant',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='queueparticipant',
            name='phone',
        ),
        migrations.AddField(
            model_name='queueparticipant',
            name='email',
            field=models.EmailField(default='noreply@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='queueparticipant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='queueparticipant',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queueapp.queue'),
        ),
    ]
